import 'package:almohsen_s_application12/widgets/custom_icon_button.dart';import 'package:almohsen_s_application12/widgets/custom_rating_bar.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application12/core/app_export.dart';import 'controller/reviews_gallery_controller.dart';class ReviewsGalleryScreen extends GetWidget<ReviewsGalleryController> {const ReviewsGalleryScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, body: Container(width: SizeUtils.width, height: SizeUtils.height, decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgReviewsGallery), fit: BoxFit.cover)), child: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 24.v), Padding(padding: EdgeInsets.only(left: 24.h), child: CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(16.h), onTap: () {onTapBtnArrowLeft();}, child: CustomImageView(imagePath: ImageConstant.imgArrowLeft))), Spacer(), _buildRefresh(), SizedBox(height: 55.v), _buildTwentyNine()]))))); } 
/// Section Widget
Widget _buildRefresh() { return SizedBox(width: double.maxFinite, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 83.v, width: 42.h, padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 30.v), decoration: AppDecoration.fillWhiteA700.copyWith(borderRadius: BorderRadiusStyle.customBorderLR18), child: CustomImageView(imagePath: ImageConstant.imgRefresh, height: 22.v, width: 23.h, alignment: Alignment.centerLeft)), Container(height: 83.v, width: 42.h, padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 30.v), decoration: AppDecoration.fillWhiteA700.copyWith(borderRadius: BorderRadiusStyle.customBorderTL18), child: CustomImageView(imagePath: ImageConstant.imgForward, height: 22.v, width: 23.h, alignment: Alignment.centerRight))])); } 
/// Section Widget
Widget _buildTwentyNine() { return Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), decoration: AppDecoration.gradientOnPrimaryToBlueGray, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.end, children: [Container(width: 159.h, margin: EdgeInsets.only(top: 190.v, bottom: 1.v), padding: EdgeInsets.symmetric(vertical: 10.v), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.circleBorder35), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [CustomImageView(imagePath: ImageConstant.imgShape28, height: 50.adaptSize, width: 50.adaptSize, radius: BorderRadius.circular(25.h)), Padding(padding: EdgeInsets.symmetric(vertical: 9.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_samuel_ella".tr, style: theme.textTheme.labelLarge), SizedBox(height: 5.v), CustomRatingBar(initialRating: 0, itemCount: 4)]))])), Padding(padding: EdgeInsets.only(top: 56.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgShape60, height: 63.v, width: 58.h, radius: BorderRadius.circular(18.h)), SizedBox(height: 8.v), CustomImageView(imagePath: ImageConstant.imgShape59, height: 63.v, width: 58.h, radius: BorderRadius.circular(18.h)), SizedBox(height: 8.v), CustomImageView(imagePath: ImageConstant.imgShape58, height: 63.v, width: 58.h, radius: BorderRadius.circular(18.h))]))])); } 

/// Navigates to the previous screen.
onTapBtnArrowLeft() { Get.back(); } 
 }
