import 'package:almohsen_s_application12/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application12/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:almohsen_s_application12/widgets/app_bar/appbar_subtitle.dart';import 'package:almohsen_s_application12/widgets/custom_text_form_field.dart';import 'models/layoutchipview_item_model.dart';import '../extra_information_screen/widgets/layoutchipview_item_widget.dart';import 'widgets/propertyfeatureslist_item_widget.dart';import 'models/propertyfeatureslist_item_model.dart';import 'models/totalroomschipview_item_model.dart';import '../extra_information_screen/widgets/totalroomschipview_item_widget.dart';import 'models/environmentfacilitieschipview_item_model.dart';import '../extra_information_screen/widgets/environmentfacilitieschipview_item_widget.dart';import 'package:almohsen_s_application12/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application12/core/app_export.dart';import 'controller/extra_information_controller.dart';import 'package:almohsen_s_application12/presentation/extra_information_success_bottomsheet/extra_information_success_bottomsheet.dart';import 'package:almohsen_s_application12/presentation/extra_information_success_bottomsheet/controller/extra_information_success_controller.dart';class ExtraInformationScreen extends GetWidget<ExtraInformationController> {const ExtraInformationScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 21.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 49.v), Expanded(child: SingleChildScrollView(child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 3.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 267.h, margin: EdgeInsets.only(left: 21.h, right: 81.h), child: Text("msg_almost_finish_complete_the".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineSmall!.copyWith(height: 1.50))), SizedBox(height: 43.v), Padding(padding: EdgeInsets.only(left: 21.h), child: Text("lbl_sell_price".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(left: 21.h, right: 27.h), child: CustomTextFormField(controller: controller.priceController, hintText: "lbl_180_000".tr, hintStyle: CustomTextStyles.labelLargeSemiBold, alignment: Alignment.center, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 25.v, 16.h, 25.v), child: CustomImageView(imagePath: ImageConstant.imgIconoirmail, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 70.v))), SizedBox(height: 37.v), Padding(padding: EdgeInsets.only(left: 21.h), child: Text("lbl_rent_price".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(left: 21.h, right: 24.h), child: CustomTextFormField(controller: controller.priceController1, hintText: "lbl_315".tr, hintStyle: CustomTextStyles.labelLargeSemiBold, textInputAction: TextInputAction.done, alignment: Alignment.center, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 25.v, 16.h, 25.v), child: CustomImageView(imagePath: ImageConstant.imgIconoirmail, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 70.v))), SizedBox(height: 15.v), _buildLayoutChipView(), SizedBox(height: 38.v), Padding(padding: EdgeInsets.only(left: 21.h), child: Text("msg_property_features".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 14.v), _buildPropertyFeaturesList(), SizedBox(height: 37.v), Padding(padding: EdgeInsets.only(left: 21.h), child: Text("lbl_total_rooms".tr, style: CustomTextStyles.titleMediumBold)), SizedBox(height: 16.v), _buildTotalRoomsChipView(), SizedBox(height: 36.v), Padding(padding: EdgeInsets.only(left: 21.h), child: Text("msg_environment_facilities".tr, style: CustomTextStyles.titleMediumBold)), SizedBox(height: 16.v), _buildEnvironmentFacilitiesChipView(), SizedBox(height: 46.v), CustomImageView(imagePath: ImageConstant.imgProgressBarGradient, height: 1.v, width: 100.h, alignment: Alignment.center)]))))])), bottomNavigationBar: _buildFinishButton())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 74.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 3.v, bottom: 3.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_add_listing".tr)); } 
/// Section Widget
Widget _buildLayoutChipView() { return Padding(padding: EdgeInsets.only(left: 21.h), child: Obx(() => Wrap(runSpacing: 3.v, spacing: 3.h, children: List<Widget>.generate(controller.extraInformationModelObj.value.layoutchipviewItemList.value.length, (index) {LayoutchipviewItemModel model = controller.extraInformationModelObj.value.layoutchipviewItemList.value[index]; return LayoutchipviewItemWidget(model);})))); } 
/// Section Widget
Widget _buildPropertyFeaturesList() { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 21.h), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 15.v);}, itemCount: controller.extraInformationModelObj.value.propertyfeatureslistItemList.value.length, itemBuilder: (context, index) {PropertyfeatureslistItemModel model = controller.extraInformationModelObj.value.propertyfeatureslistItemList.value[index]; return PropertyfeatureslistItemWidget(model);})))); } 
/// Section Widget
Widget _buildTotalRoomsChipView() { return Align(alignment: Alignment.centerRight, child: Obx(() => Wrap(runSpacing: 10.v, spacing: 10.h, children: List<Widget>.generate(controller.extraInformationModelObj.value.totalroomschipviewItemList.value.length, (index) {TotalroomschipviewItemModel model = controller.extraInformationModelObj.value.totalroomschipviewItemList.value[index]; return TotalroomschipviewItemWidget(model);})))); } 
/// Section Widget
Widget _buildEnvironmentFacilitiesChipView() { return Align(alignment: Alignment.center, child: Obx(() => Wrap(runSpacing: 4.v, spacing: 4.h, children: List<Widget>.generate(controller.extraInformationModelObj.value.environmentfacilitieschipviewItemList.value.length, (index) {EnvironmentfacilitieschipviewItemModel model = controller.extraInformationModelObj.value.environmentfacilitieschipviewItemList.value[index]; return EnvironmentfacilitieschipviewItemWidget(model);})))); } 
/// Section Widget
Widget _buildFinishButton() { return CustomElevatedButton(text: "lbl_finish".tr, margin: EdgeInsets.only(left: 25.h, right: 23.h, bottom: 24.v), onPressed: () {onTapFinishButton();}); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 

/// Displays a scrollable bottom sheet widget using the [Get] package 
/// and the [ExtraInformationSuccessBottomsheet] widget.
///
/// The bottom sheet is controlled by the [ExtraInformationSuccessController]
/// and is displayed using the [Get.bottomSheet] method with
/// [isScrollControlled] set to true.

onTapFinishButton() { Get.bottomSheet(ExtraInformationSuccessBottomsheet(Get.put(ExtraInformationSuccessController(),),),isScrollControlled: true,); } 
 }
