import 'package:almohsen_s_application12/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application12/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:almohsen_s_application12/widgets/app_bar/appbar_subtitle.dart';import 'package:almohsen_s_application12/widgets/custom_icon_button.dart';import 'package:almohsen_s_application12/widgets/custom_elevated_button.dart';import 'package:almohsen_s_application12/widgets/custom_text_form_field.dart';import 'widgets/paymentmethodlist_item_widget.dart';import 'models/paymentmethodlist_item_model.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application12/core/app_export.dart';import 'controller/review_fill_controller.dart';class ReviewFillScreen extends GetWidget<ReviewFillController> {const ReviewFillScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 21.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 17.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [_buildEstatesCardTransaction(), SizedBox(height: 37.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_period".tr, style: theme.textTheme.titleMedium))), SizedBox(height: 16.v), _buildFormDateFill(), SizedBox(height: 37.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_note_for_owner".tr, style: theme.textTheme.titleMedium))), SizedBox(height: 16.v), _buildTelevisionEditText(), SizedBox(height: 39.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_payment_method".tr, style: theme.textTheme.titleMedium))), SizedBox(height: 14.v), _buildPaymentMethodList(), SizedBox(height: 36.v), _buildItemHeaderRow(), SizedBox(height: 16.v), _buildCardCoupon(), SizedBox(height: 50.v), CustomImageView(imagePath: ImageConstant.imageNotFound, height: 1.v, width: 100.h)]))))])), bottomNavigationBar: _buildNext())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 74.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 3.v, bottom: 3.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "msg_transaction_review".tr)); } 
/// Section Widget
Widget _buildApartmentButton() { return CustomElevatedButton(height: 24.v, width: 72.h, text: "lbl_apartment".tr, leftIcon: Container(margin: EdgeInsets.only(right: 6.h), child: CustomImageView(imagePath: ImageConstant.imgClose, height: 13.v, width: 11.h)), buttonStyle: CustomButtonStyles.fillBlueGrayAfTL8, buttonTextStyle: CustomTextStyles.labelSmallGray100); } 
/// Section Widget
Widget _buildRentButton() { return CustomElevatedButton(height: 50.v, width: 94.h, text: "lbl_rent".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgClose, height: 18.v, width: 15.h)), buttonStyle: CustomButtonStyles.fillWhiteATL25, buttonTextStyle: theme.textTheme.labelMedium!, alignment: Alignment.centerRight); } 
/// Section Widget
Widget _buildEstatesCardTransaction() { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.all(8.h), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Row(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 140.v, width: 168.h, child: Stack(alignment: Alignment.centerLeft, children: [CustomImageView(imagePath: ImageConstant.imgShape20, height: 140.v, width: 168.h, radius: BorderRadius.circular(18.h), alignment: Alignment.center), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 8.h, right: 88.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomIconButton(height: 25.adaptSize, width: 25.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillWhiteATL121, child: CustomImageView(imagePath: ImageConstant.imgFavoriteRedA200)), SizedBox(height: 75.v), _buildApartmentButton()])))])), Padding(padding: EdgeInsets.fromLTRB(16.h, 8.v, 9.h, 8.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 88.h, child: Text("msg_sky_dandelions_apartment".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.50))), SizedBox(height: 6.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgLinkedin, height: 12.adaptSize, width: 12.adaptSize), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("msg_jakarta_indonesia".tr, style: theme.textTheme.labelSmall))]), SizedBox(height: 18.v), _buildRentButton()]))])); } 
/// Section Widget
Widget _buildStartDateEditText() { return CustomTextFormField(width: 163.h, controller: controller.startDateEditTextController, hintText: "lbl_11_28_2021".tr, hintStyle: CustomTextStyles.labelLargeSemiBold, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 25.v, 16.h, 25.v), child: CustomImageView(imagePath: ImageConstant.imgCalendar, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 70.v)); } 
/// Section Widget
Widget _buildEndDateEditText() { return Padding(padding: EdgeInsets.only(left: 6.h), child: CustomTextFormField(width: 160.h, controller: controller.endDateEditTextController, hintText: "lbl_01_28_2022".tr, hintStyle: CustomTextStyles.labelLargeSemiBold, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 25.v, 16.h, 25.v), child: CustomImageView(imagePath: ImageConstant.imgCalendar, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 70.v))); } 
/// Section Widget
Widget _buildFormDateFill() { return Padding(padding: EdgeInsets.symmetric(horizontal: 23.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildStartDateEditText(), _buildEndDateEditText()])); } 
/// Section Widget
Widget _buildTelevisionEditText() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: CustomTextFormField(controller: controller.televisionEditTextController, hintText: "msg_please_clean_before".tr, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 25.v, 16.h, 25.v), child: CustomImageView(imagePath: ImageConstant.imgTelevision, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 70.v))); } 
/// Section Widget
Widget _buildPaymentMethodList() { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 180.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: controller.reviewFillModelObj.value.paymentmethodlistItemList.value.length, itemBuilder: (context, index) {PaymentmethodlistItemModel model = controller.reviewFillModelObj.value.paymentmethodlistItemList.value[index]; return PaymentmethodlistItemWidget(model);})))); } 
/// Section Widget
Widget _buildItemHeaderRow() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_have_a_voucher".tr, style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.only(top: 4.v, bottom: 2.v), child: Text("lbl_change_voucher".tr, style: CustomTextStyles.labelLargePrimary))])); } 
/// Section Widget
Widget _buildHlwn40Button() { return CustomElevatedButton(height: 52.v, width: 128.h, text: "lbl_hlwn40".tr, margin: EdgeInsets.only(bottom: 1.v), buttonStyle: CustomButtonStyles.fillGreenATL17, buttonTextStyle: CustomTextStyles.titleMediumMontserratWhiteA700Bold); } 
/// Section Widget
Widget _buildCardCoupon() { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.all(16.h), decoration: AppDecoration.gradientGreenAToTealA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Row(mainAxisSize: MainAxisSize.max, children: [_buildHlwn40Button(), Padding(padding: EdgeInsets.only(left: 10.h, top: 10.v, bottom: 10.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_halloween_sale".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), Text("msg_get_40_off_on_all".tr, style: theme.textTheme.labelSmall)]))])); } 
/// Section Widget
Widget _buildNext() { return CustomElevatedButton(text: "lbl_next".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 24.v), onPressed: () {onTapNext();}); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the summaryScreen when the action is triggered.
onTapNext() { Get.toNamed(AppRoutes.summaryScreen, ); } 
 }
