import 'package:almohsen_s_application12/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application12/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:almohsen_s_application12/widgets/app_bar/appbar_trailing_button.dart';import 'package:almohsen_s_application12/presentation/payment_empty_page/payment_empty_page.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application12/core/app_export.dart';import 'controller/payment_empty_tab_container_controller.dart';class PaymentEmptyTabContainerScreen extends GetWidget<PaymentEmptyTabContainerController> {const PaymentEmptyTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 50.v), Container(width: 226.h, margin: EdgeInsets.only(left: 24.h), child: Text("msg_add_your_payment".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineSmall!.copyWith(height: 1.50))), SizedBox(height: 24.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Text("msg_you_can_edit_this".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 54.v), _buildWalletEmpty(), SizedBox(height: 15.v), _buildTabview(), _buildTabBarView()])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 74.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 3.v, bottom: 3.v), onTap: () {onTapArrowLeft();}), actions: [AppbarTrailingButton(margin: EdgeInsets.fromLTRB(24.h, 10.v, 24.h, 8.v), onTap: () {onTapSkip();})]); } 
/// Section Widget
Widget _buildWalletEmpty() { return Align(alignment: Alignment.center, child: Card(clipBehavior: Clip.antiAlias, elevation: 0, color: appTheme.blueGray80001, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder25), child: Container(height: 180.v, width: 327.h, decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgSubtractWhiteA700, height: 97.v, width: 130.h, alignment: Alignment.topRight), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_your_name".tr, style: CustomTextStyles.titleSmallWhiteA700), SizedBox(height: 41.v), Text("msg".tr, style: CustomTextStyles.titleMediumWhiteA700_1), SizedBox(height: 22.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_balance".tr, style: CustomTextStyles.labelSmallWhiteA700), SizedBox(height: 4.v), Text("lbl5".tr, style: CustomTextStyles.titleSmallWhiteA700_1)]), CustomImageView(imagePath: ImageConstant.imgThumbsUpWhiteA700, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 7.v, bottom: 3.v))])])))])))); } 
/// Section Widget
Widget _buildTabview() { return Container(height: 50.v, width: 368.h, child: TabBar(controller: controller.tabviewController, isScrollable: true, tabs: [Tab(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgTelevisionIndigo90020x20, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 3.v), child: Text("lbl_paypal".tr))])), Tab(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgUser11x20, height: 11.v, width: 20.h, margin: EdgeInsets.only(top: 1.v, bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_mastercard".tr))])), Tab(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgSettingsIndigo90001, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 2.v, bottom: 2.v), child: Text("lbl_visa".tr))]))])); } 
/// Section Widget
Widget _buildTabBarView() { return Expanded(child: SizedBox(height: 272.v, child: TabBarView(controller: controller.tabviewController, children: [PaymentEmptyPage(), PaymentEmptyPage(), PaymentEmptyPage()]))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the homeContainerScreen when the action is triggered.
onTapSkip() { Get.toNamed(AppRoutes.homeContainerScreen, ); } 
 }
