import 'package:almohsen_s_application12/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application12/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:almohsen_s_application12/widgets/app_bar/appbar_subtitle.dart';import 'package:almohsen_s_application12/widgets/custom_rating_bar.dart';import 'package:almohsen_s_application12/widgets/custom_text_form_field.dart';import 'package:almohsen_s_application12/widgets/custom_icon_button.dart';import 'package:almohsen_s_application12/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application12/core/app_export.dart';import 'controller/add_review_empty_controller.dart';class AddReviewEmptyScreen extends GetWidget<AddReviewEmptyController> {const AddReviewEmptyScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 49.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 272.h, margin: EdgeInsets.only(right: 55.h), child: Text("msg_hi_how_was_your".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineSmall!.copyWith(height: 1.50))), SizedBox(height: 27.v), Text("msg_lorem_ipsum_dolor6".tr, style: theme.textTheme.bodySmall), SizedBox(height: 52.v), Padding(padding: EdgeInsets.only(right: 41.h), child: Row(children: [CustomRatingBar(initialRating: 0, itemSize: 40), Padding(padding: EdgeInsets.only(left: 15.h, top: 4.v, bottom: 4.v), child: Text("lbl_0_0".tr, style: CustomTextStyles.headlineSmallMontserrat))])), SizedBox(height: 20.v), CustomTextFormField(controller: controller.formTextareaController, hintText: "msg_write_your_experience".tr, hintStyle: CustomTextStyles.bodySmallOnPrimaryContainer, textInputAction: TextInputAction.done, maxLines: 7, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 18.v)), SizedBox(height: 15.v), CustomIconButton(height: 78.adaptSize, width: 78.adaptSize, padding: EdgeInsets.all(29.h), child: CustomImageView(imagePath: ImageConstant.imgIconPlus)), SizedBox(height: 5.v)])), bottomNavigationBar: _buildSubmit())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 74.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 3.v, bottom: 3.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_add_review".tr)); } 
/// Section Widget
Widget _buildSubmit() { return CustomElevatedButton(text: "lbl_submit".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 24.v), onPressed: () {onTapSubmit();}); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the addReviewFillScreen when the action is triggered.
onTapSubmit() { Get.toNamed(AppRoutes.addReviewFillScreen, ); } 
 }
