import 'package:almohsen_s_application12/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application12/widgets/app_bar/appbar_subtitle.dart';import 'package:almohsen_s_application12/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:almohsen_s_application12/widgets/custom_icon_button.dart';import 'package:almohsen_s_application12/presentation/listings_page/listings_page.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application12/core/app_export.dart';import 'controller/transaction_tab_container_controller.dart';import 'models/transaction_tab_container_model.dart';
// ignore_for_file: must_be_immutable
class TransactionTabContainerPage extends StatelessWidget {TransactionTabContainerPage({Key? key}) : super(key: key);

TransactionTabContainerController controller = Get.put(TransactionTabContainerController(TransactionTabContainerModel().obs));

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 17.v), SizedBox(height: 100.adaptSize, width: 100.adaptSize, child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgShape34, height: 100.adaptSize, width: 100.adaptSize, radius: BorderRadius.circular(50.h), alignment: Alignment.center), CustomIconButton(height: 30.adaptSize, width: 30.adaptSize, padding: EdgeInsets.all(9.h), decoration: IconButtonStyleHelper.fillBlueGrayTL15, alignment: Alignment.bottomRight, onTap: () {onTapBtnEdit();}, child: CustomImageView(imagePath: ImageConstant.imgEdit))])), SizedBox(height: 11.v), Text("msg_jonathan_anderson".tr, style: CustomTextStyles.titleSmallBold), SizedBox(height: 7.v), Text("msg_jonathan_email_com".tr, style: CustomTextStyles.labelMediumBluegray600SemiBold), SizedBox(height: 13.v), _buildInformationReviews(), SizedBox(height: 20.v), _buildTabview(), _buildTabBarView()])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(centerTitle: true, title: AppbarSubtitle(text: "lbl_profile".tr), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgSearch, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 3.v))]); } 
/// Section Widget
Widget _buildInformationReviews() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildInformationReviewsSold(text: "lbl_30".tr, sold: "lbl_listings2".tr), Padding(padding: EdgeInsets.only(left: 10.h), child: _buildInformationReviewsSold(text: "lbl_12".tr, sold: "lbl_sold".tr)), Padding(padding: EdgeInsets.only(left: 10.h), child: _buildInformationReviewsSold(text: "lbl_28".tr, sold: "lbl_reviews".tr))])); } 
/// Section Widget
Widget _buildTabview() { return Container(height: 50.v, width: 327.h, decoration: BoxDecoration(color: appTheme.gray100, borderRadius: BorderRadius.circular(25.h)), child: TabBar(controller: controller.tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.blueGray80001, labelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Raleway', fontWeight: FontWeight.w600), unselectedLabelColor: theme.colorScheme.onPrimaryContainer, unselectedLabelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Raleway', fontWeight: FontWeight.w600), indicatorPadding: EdgeInsets.all(9.0.h), indicator: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(16.h)), tabs: [Tab(child: Text("lbl_transaction".tr)), Tab(child: Text("lbl_listings2".tr)), Tab(child: Text("lbl_sold".tr))])); } 
/// Section Widget
Widget _buildTabBarView() { return Expanded(child: SizedBox(height: 326.v, child: TabBarView(controller: controller.tabviewController, children: [ListingsPage(), ListingsPage(), ListingsPage()]))); } 
/// Common widget
Widget _buildInformationReviewsSold({required String text, required String sold, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 36.h, vertical: 14.v), decoration: AppDecoration.outlineBluegray50.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [Text(text, style: CustomTextStyles.titleSmallBold.copyWith(color: appTheme.blueGray80001)), SizedBox(height: 5.v), Text(sold, style: CustomTextStyles.labelLargeBluegray600.copyWith(color: appTheme.blueGray600))])); } 
/// Navigates to the editProfileScreen when the action is triggered.
onTapBtnEdit() { Get.toNamed(AppRoutes.editProfileScreen, ); } 
 }
