import 'package:almohsen_s_application12/widgets/custom_text_form_field.dart';import 'package:almohsen_s_application12/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application12/core/app_export.dart';import 'controller/payment_mastercard_controller.dart';import 'models/payment_mastercard_model.dart';
// ignore_for_file: must_be_immutable
class PaymentMastercardPage extends StatelessWidget {PaymentMastercardPage({Key? key}) : super(key: key);

PaymentMastercardController controller = Get.put(PaymentMastercardController(PaymentMastercardModel().obs));

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: _buildScrollView())); } 
/// Section Widget
Widget _buildScrollView() { return SingleChildScrollView(child: Column(children: [SizedBox(height: 20.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [CustomTextFormField(controller: controller.lockController, hintText: "msg_jonathan_anderson".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 25.v, 16.h, 25.v), decoration: BoxDecoration(borderRadius: BorderRadius.vertical(bottom: Radius.circular(50.h))), child: CustomImageView(imagePath: ImageConstant.imgLockBlueGray80001, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 70.v)), SizedBox(height: 15.v), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 25.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text("msg_1222_3443_9881_1222".tr, style: theme.textTheme.titleSmall)), CustomImageView(imagePath: ImageConstant.imgThumbsUpBlueGray80001, height: 20.adaptSize, width: 20.adaptSize)])), SizedBox(height: 15.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: GestureDetector(onTap: () {onTapFormDateFill();}, child: Container(margin: EdgeInsets.only(right: 5.h), padding: EdgeInsets.symmetric(vertical: 25.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Obx(() => Text(controller.paymentMastercardModelObj.value.date.value, style: theme.textTheme.titleSmall))), CustomImageView(imagePath: ImageConstant.imgCalendar, height: 20.adaptSize, width: 20.adaptSize)])))), Container(margin: EdgeInsets.only(left: 5.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 25.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder12), child: CustomTextFormField(width: 59.h, controller: controller.cvvController, hintText: "lbl_cvv".tr, hintStyle: CustomTextStyles.bodyMediumOnPrimaryContainer, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.only(right: 10.h), child: CustomImageView(imagePath: ImageConstant.imgThumbsUpBlueGray80001, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 20.v), contentPadding: EdgeInsets.symmetric(vertical: 1.v)))]), SizedBox(height: 30.v), CustomImageView(imagePath: ImageConstant.imageNotFound, height: 1.v, width: 100.h), SizedBox(height: 10.v), CustomElevatedButton(text: "lbl_next".tr, onPressed: () {onTapNext();})]))])); } 

/// Displays a date picker dialog and updates the selected date in the
/// [paymentMastercardModelObj] object of the current [date] if the user 
/// selects a valid date.
///
/// This function returns a `Future` that completes with `void`.
Future<void> onTapFormDateFill() async  { DateTime? dateTime  = await showDatePicker(context: Get.context!,initialDate: controller.paymentMastercardModelObj.value.selectedDate!.value , firstDate: DateTime(1970) ,lastDate: DateTime(DateTime.now().year,DateTime.now().month,DateTime.now().day)); if (dateTime != null) {controller.paymentMastercardModelObj.value.selectedDate!.value = dateTime;controller.paymentMastercardModelObj.value.date.value = dateTime.format(pattern: SHORT_DATE_WITH_FULL_YEAR);} } 
/// Navigates to the userEmptyScreen when the action is triggered.
onTapNext() { Get.toNamed(AppRoutes.userEmptyScreen, ); } 
 }
