import 'package:almohsen_s_application12/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application12/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:almohsen_s_application12/widgets/app_bar/appbar_subtitle.dart';import 'package:almohsen_s_application12/widgets/custom_text_form_field.dart';import 'models/chipviewlayout1_item_model.dart';import '../form_detail_screen/widgets/chipviewlayout1_item_widget.dart';import 'models/chipviewlayout3_item_model.dart';import '../form_detail_screen/widgets/chipviewlayout3_item_widget.dart';import 'package:almohsen_s_application12/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application12/core/app_export.dart';import 'controller/form_detail_controller.dart';class FormDetailScreen extends GetWidget<FormDetailController> {const FormDetailScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 11.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 38.v), Container(width: 281.h, margin: EdgeInsets.only(left: 17.h, right: 62.h), child: Text("msg_hi_josh_fill_detail".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineSmall!.copyWith(height: 1.50))), SizedBox(height: 40.v), Padding(padding: EdgeInsets.symmetric(horizontal: 17.h), child: CustomTextFormField(controller: controller.formPasswordController, hintText: "lbl_the_lodge_house".tr, hintStyle: theme.textTheme.labelLarge!, textInputAction: TextInputAction.done, alignment: Alignment.center, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 25.v, 16.h, 25.v), decoration: BoxDecoration(borderRadius: BorderRadius.vertical(bottom: Radius.circular(50.h))), child: CustomImageView(imagePath: ImageConstant.imgHomeBlueGray80001, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 70.v))), SizedBox(height: 33.v), Padding(padding: EdgeInsets.only(left: 17.h), child: Text("lbl_listing_type".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 20.v), _buildChipViewLayout1(), SizedBox(height: 29.v), Padding(padding: EdgeInsets.only(left: 17.h), child: Text("msg_property_category".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 20.v), _buildChipViewLayout2(), SizedBox(height: 79.v), CustomImageView(imagePath: ImageConstant.imageNotFound, height: 1.v, width: 100.h, alignment: Alignment.center)])), bottomNavigationBar: _buildNextButton())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 74.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 3.v, bottom: 3.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_add_listing".tr)); } 
/// Section Widget
Widget _buildChipViewLayout1() { return Padding(padding: EdgeInsets.only(left: 16.h), child: Obx(() => Wrap(runSpacing: 7.v, spacing: 7.h, children: List<Widget>.generate(controller.formDetailModelObj.value.chipviewlayout1ItemList.value.length, (index) {Chipviewlayout1ItemModel model = controller.formDetailModelObj.value.chipviewlayout1ItemList.value[index]; return Chipviewlayout1ItemWidget(model);})))); } 
/// Section Widget
Widget _buildChipViewLayout2() { return Padding(padding: EdgeInsets.only(left: 17.h), child: Obx(() => Wrap(runSpacing: 5.v, spacing: 5.h, children: List<Widget>.generate(controller.formDetailModelObj.value.chipviewlayout3ItemList.value.length, (index) {Chipviewlayout3ItemModel model = controller.formDetailModelObj.value.chipviewlayout3ItemList.value[index]; return Chipviewlayout3ItemWidget(model);})))); } 
/// Section Widget
Widget _buildNextButton() { return CustomElevatedButton(text: "lbl_next".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 24.v), onPressed: () {onTapNextButton();}); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the addLocationScreen when the action is triggered.
onTapNextButton() { Get.toNamed(AppRoutes.addLocationScreen, ); } 
 }
